google/subpar

- compiler/cli.py
- compiler/python_archive.py
- compiler/python_archive_test.py
- tests/BUILD
- tests/package_import_roots/import_roots.py
- tests/package_import_roots/import_roots_PY2_filelist.txt
- tests/package_import_roots/import_roots_PY3_filelist.txt
This is based on #13.  I moved the code to a place I felt was slightly better, and added some tests.  Some tweaks were also required for Python3.
> Extend import_roots to also automatically include workspace roots.

- README.md
The 'sha256' attribute is documented but doesn't seem to actually work.
> Fix git_repository example

- subpar.bzl
This makes it possible to run py_tests as .par files, which is occasionally useful for testing code that behaves differently when called from within a zipped executable.  It also enables the uncommon (but valid, I'm pretty sure) scenario of having a par_binary definition with `testonly=True` set.
> Add par_test variant of par_binary, passthrough testonly attr

- compiler/python_archive.py
- test_dir_shadowing/BUILD
- test_dir_shadowing/test_dir_shadowing/dir_shadowing_lib.py
- test_dir_shadowing/test_dir_shadowing/dir_shadowing_lib_dat.txt
- test_dir_shadowing/test_dir_shadowing/dir_shadowing_main.py
- test_dir_shadowing/test_dir_shadowing/dir_shadowing_main_dat.txt
- test_dir_shadowing/test_dir_shadowing_main_PY2_filelist.txt
- test_dir_shadowing/test_dir_shadowing_main_PY3_filelist.txt
- tests/BUILD
> Retain Bazel's ordering of Python import paths

- .flake8
- .gitignore
- compiler/error.py
- compiler/python_archive.py
- compiler/python_archive_test.py
- nox.py
- runtime/support_test.py
- test_dir_shadowing/test_dir_shadowing/dir_shadowing_lib.py
- test_dir_shadowing/test_dir_shadowing/dir_shadowing_main.py
- tests/package_a/a.py
- tests/package_d/d.py
- tests/package_f/f_PY2.py
- tests/package_f/f_PY3.py
- tests/package_import_roots/import_roots.py
- tests/package_shadow/main.py
> Add linter config and fix all lint warnings.

- runtime/support.py
- runtime/support_test.py
- tests/package_pkg_resources/main.py
- tests/package_pkg_resources/main_PY2_filelist.txt
- tests/package_pkg_resources/main_PY3_filelist.txt
- third_party/pypi__portpicker_1_2_0/BUILD
- third_party/pypi__portpicker_1_2_0/data_file.txt
- third_party/pypi__portpicker_1_2_0/portpicker.py
- third_party/pypi__yapf_0_19_0/BUILD
- third_party/pypi__yapf_0_19_0/data_file.txt
- third_party/pypi__yapf_0_19_0/yapf/__init__.py
Several limitations apply.
Fixes #38 
Partially addresses #43
> Allow pkg_resources' resource APIs to be used inside .par files.

- compiler/python_archive.py
- compiler/python_archive_test.py
- tests/BUILD
- tests/package_boilerplate/main.py
- tests/package_boilerplate/main_PY2_filelist.txt
- tests/package_boilerplate/main_PY3_filelist.txt
- tests/package_g/g.py
- tests/package_g/g_PY2_filelist.txt
- tests/package_g/g_PY3_filelist.txt
> Fix handling of module doc comments in main source file

- runtime/support.py
Sometimes the archive path is relative while sys.path[0] is absolute, or vice versa. This allows `setup()` to work in both cases
> Make paths absolute before comparing

- subpar.bzl
This is useful for custom compilers. In mine, I have a 'lite' mode that replaces the runtime library and removes unused files from the par to make it very light (but only support 100% Python archives as a result).
> Handle extra arguments to pass to the compiler

- compiler/python_archive_test.py
- tests/test_harness.sh
Two issues:
- BSD head/tail don't support the +/- specifications. Use "-q -q" to unzip instead
to remove headers and footers.
- "python2" isn't guaranteed to exist. Use the current interpreter.
> Fix tests on MacOS.

- run_tests.sh
Fixed usage of `expr` that is not supported on Mac OS.
Fixed case when $(which python3) returned false.
> Minor fixes and cleanups to run_tests.sh script

- compiler/python_archive.py
we have a mixed 2.6, 2.7 env and bazel picks up python 2.6 on some of our containers. the only issue we have is this part of the code. this patch will fix that
> make python_archive compatible with python 2.6

- subpar.bzl
Tested:
`bazel0.20 test //... --all_incompatible_changes`
- Reformatted file with Buildifier
- Applied Buildifier automated fixes
- Fixed other issues (depsets are not iterable, tools are separate from other inputs)
Progress towards https://github.com/bazelbuild/rules_python/issues/134
> Cleanup for Bazel future changes

- compiler/cli.py
- compiler/cli_test.py
In case the Python runtime used to build a par is not exactly the same path as the target interpreter, this allows the interpreter to be explicitly set instead of inferred from the stub file.
Example:
```python
par_binary(
name = "mybinary",
srcs = ["mybinary.py"],
compiler_args = ["--interpreter", "/usr/bin/env python3.6"],
)
```
> Python interpreter can now be overridden

- compiler/BUILD
- subpar.bzl
This gets `bazel build //... --all_incompatible_changes` working with Bazel 0.23.
("Diffbased" on #95, but I don't know what the equivalent of diffbase is in github if any. Just ignore the docgen commit in this PR.)
**Edit:** To confirm and save you some time, the content of this PR is just 2 changed lines.
> Fixes for --all_incompatible_changes

- compiler/cli.py
- compiler/cli_test.py
- compiler/python_archive.py
- subpar.bzl
Fixes #98 by detecting the default toolchain wrappers and replacing with env versions. I'm perhaps not totally happy with how it's done, as any change in the path to these wrappers would break things again, so open to suggestions. Also, for Python 2 should we use `/usr/bin/python` or `/usr/bin/python2`, I prefer the latter but don't know how this behaves on all systems?
Also, now that we have PyInfo provider, the import paths are passed directly from Starlark to the compiler, removing a bit of fragility in parsing the stub file for those. However, I can't see a way to pass the interpreter directly, as this doesn't appear to be available to Starlark. This removed a TODO with reference `b/29227737`, if that means anything internally?
Tested with both the default toolchain and a custom one …
> Fix incompatibility with Python Toolchains

- run_tests.sh
- tests/BUILD
- tests/package_f/f_PY3.py
- toolchain_test_hook.bzl
This adds a hook file for run_tests.sh to write toolchain info to before each bazel invocation. This replaces the legacy way of passing an interpreter in via --python_path.
It also replaces a config_setting that was used to control whether PY2 or PY3 was used, with a simple constant symbol consumed at loading time. This is needed in order to make the target aware at analysis time of which version it is building for.
Fixes #98, fixes #102.
> Fix tests for --incompatible_use_python_toolchains

- .bazelrc
- run_tests.sh
- tests/test_harness.sh
@tmc, care to review / rubber stamp?
> Fix test failures when running directly instead of via script

- WORKSPACE
This will be useful to keep up-to-date for documentation purposes, and so we
know when a release cut breaks compatibility with Bazel and therefore needs to
be a major release.
> Add note on bazel version compatibility to WORKSPACE

- WORKSPACE
- compiler/BUILD
- run_tests.sh
- runtime/BUILD
- subpar.bzl
- test_dir_shadowing/BUILD
- tests/package_a/BUILD
- tests/test_workspace/BUILD
- tests/test_workspace/WORKSPACE
- third_party/pypi__portpicker_1_2_0/BUILD
- third_party/pypi__portpicker_1_2_0/WORKSPACE
- third_party/pypi__yapf_0_19_0/BUILD
- third_party/pypi__yapf_0_19_0/WORKSPACE
This migrates subpar for bazelbuild/bazel#9006. Note that it adds a dependency
on bazelbuild/rules_python, which means that these two repositories now have a
dependency cycle.
WORKSPACE and BUILD files in tests are also updated for the same.
> Load Python rules from bazelbuild/rules_python

- subpar.bzl
This updates the `par_***` macros to propagate tags to the underlying rules. This is important, as currently the `manual` tag doesn't work fro the `par_***` macros.
> Propagate tags via par_*** macros
